# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 22:16
from __future__ import unicode_literals

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='data_header', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Itinerary',
                'verbose_name_plural': 'Itineraries',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='data_link', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('sub_title', models.TextField(max_length=500, verbose_name='Sub Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('url', models.URLField(max_length=50, verbose_name='URL')),
                ('video', models.FileField(blank=True, null=True, upload_to='news', verbose_name='Video')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='data_news', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('sub_title', models.TextField(max_length=500, verbose_name='Sub Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('owner', models.CharField(max_length=100, verbose_name='Owner')),
                ('url', models.URLField(max_length=50, verbose_name='URL')),
                ('video', models.FileField(blank=True, null=True, upload_to='news', verbose_name='Video')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='data_service', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('sub_title', models.CharField(max_length=500, verbose_name='Sub Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('latitude', models.FloatField(default=0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0, verbose_name='Longitude')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('day', models.IntegerField(default=1, verbose_name='N\xb0 Days')),
                ('night', models.IntegerField(default=1, verbose_name='N\xb0 Nights')),
                ('max_people', models.IntegerField(default=0, verbose_name='Max. People')),
                ('ranking', models.BooleanField(default=False, verbose_name='Ranking')),
                ('publish', models.BooleanField(default=False, verbose_name='Publish')),
                ('image1', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image1')),
                ('image2', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image2')),
                ('image3', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image3')),
                ('itinerary', models.ManyToManyField(to='Data.Itinerary', verbose_name='Itinerary')),
                ('page', cms.models.fields.PageField(blank=True, help_text='Wraps the image in a link to an internal (page) URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Internal URL')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='data_slide', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Sub title')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='data_title', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title2', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='service',
            name='suggestion',
            field=models.ManyToManyField(to='Data.Suggestion', verbose_name='Suggestion'),
        ),
    ]
